name: Publish new version

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

env:
    NODE_VERSION: 16.x
    APP_VERSION: ${{github.ref_name}}

jobs:
    publish:
        if: github.repository_owner == 'AxaGuilDEv'
        environment:
            name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  registry-url: 'https://registry.npmjs.org'
                  cache: 'npm'
            - run: npm ci
            - run: npm run build
            - name: Publish release packages to npm
              run: npm publish --registry https://registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    release:
        runs-on: ubuntu-latest
        needs: publish
        steps:
            - name: Create Github release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.APP_VERSION }}
                  release_name: Release ${{ env.RELEASE_VERSION }}
                  draft: false
                  prerelease: false
